### ISSUE TITLE
Upgrade Java version in Kubernetes CI for SCXA

### ISSUE THREAD

**Issue by ke4** [ebi-gene-expression-group/atlas-web-single-cell#474]
For using Java 17 locally and able to push it to the CI server, we have to change the Java version in GKE where we run our CI for Single Cell Web app. 
Our GKE Project for our CI pipeline for for Single Cell Expression Atlas can be found here: [dev-autopilot-cluster](https://console.cloud.google.com/kubernetes/list/overview?project=prj-int-dev-atlas-app-intg)
Our repo for the yaml files defines that env is here: https://github.com/ebi-gene-expression-group/atlas-k8s-ci-environment

Subtasks:
- [ ] Change the Java version from Java 11 to Java 17 
- [ ] Test if everything works correctly

**Comment by ke4** [comment]
Could use an image from here: https://hub.docker.com/_/openjdk/tags?page_size=&ordering=last_updated&name=17.0.2
Need to decide/test which one.
Maybe: [17.0.2](https://hub.docker.com/layers/library/openjdk/17.0.2/images/sha256-98f0304b3a3b7c12ce641177a99d1f3be56f532473a528fda38d53d519cafb13?context=explore)

**Comment by ke4** [comment]
Where to change JDK11 to 17 in our k8s repo:
- [ ] https://github.com/search?q=repo%3Aebi-gene-expression-group%2Fatlas-k8s-ci-environment%20jdk&type=code

Also in the `SCXA` repo:
- [ ] jenkins-k8s-pod.yaml

**Comment by ke4** [comment]
We can't do this change while we have not fixed and released these important bugs:

- [ ] [Overlapping names in the marker gene heat map](https://github.com/ebi-gene-expression-group/atlas-components/issues/173)
- [ ] [Make the inferred cell type options dynamic shown or disabled in marker gene heatmap dropdown menu](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/465)
- [ ] [Add url decoder for cell type heatmap search bug fix testing and fix in the current develop branch if it is broken](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/467)
- [ ] [Add link to the experiment accessions in the marker gene heat map for the CTW](https://github.com/ebi-gene-expression-group/atlas-components/issues/172)
